title: Project
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: project_description
        field:
          antlers: false
          display: 'Project Description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: images
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: Images
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
